### ISSUE TITLE
status_desc text in function Get-DatabaseBackupStatus incorrect for first warning condition

### ISSUE THREAD

**Issue by SQLGB** [PatrickKeisler/SQLMorningHealthChecks#1]
In the Get-DatabaseBackupStatus function, the status_desc text for the first warning condition is incorrect; the test is correct, it's just the output string for the test which is incorrect:

Line 547 currently reads:
`WHEN [D] < DATEADD(DD,-1,CURRENT_TIMESTAMP) AND [I] < DATEADD(DD,-1,CURRENT_TIMESTAMP) THEN 'FULL backup > 7 day; DIFF backup > 1 day'		-- if last_full_backup is more than 1 day old and last_differential_backup is greater than 1 days old then warning`

Line 547 should be changed to:
`WHEN [D] < DATEADD(DD,-1,CURRENT_TIMESTAMP) AND [I] < DATEADD(DD,-1,CURRENT_TIMESTAMP) THEN 'FULL backup > 1 day; DIFF backup > 1 day'		-- if last_full_backup is more than 1 day old and last_differential_backup is greater than 1 days old then warning`

**Comment by PatrickKeisler** [comment]
This was by design, which assumes you are doing a weekly FULL and daily DIFFs. Therefore if you haven't done a full backup in the last 7 days or a diff in the last 2 days, then rate it as critical. However, your environment may require updated thresholds, so feel free to alter them as needed.
