### ISSUE TITLE
Format in HTML and Send Email

### ISSUE THREAD

**Issue by Kamy79** [PatrickKeisler/SQLMorningHealthChecks#3]
Hello,
How can we enhance the script by formatting the output to HTML and sending it as email?
This will be very handy as we can schedule the script as a job and have it as email every morning to view it.
Appreciate if this can be enhanced.
Thanks
Kamal

**Comment by PatrickKeisler** [comment]
That is beyond the scope of what was intended for this script; however, please feel free to fork the code and alter it to your needs.
